---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-url-shortener
spec:
  selector:
    matchLabels:
      app: webtools-url-shortener
  replicas: 1
  template:
    metadata:
      labels:
        app: webtools-url-shortener
    spec:
      containers:
      - name: webtools-url-shortener
        image: "ikoyski/webtools-url-shortener:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8191
---
apiVersion: v1
kind: Service
metadata:
  name: webtools-url-shortener
spec:
  selector:
    app: webtools-url-shortener
  ports:
  - protocol: "TCP"
    port: 8191
    targetPort: 8191
  type: NodePort
  